kind: "Service"
apiVersion: "v1"
metadata:
  name: "logcso-prod-ext-rcdn-svc"
spec:
  ports:
    - name: "web"
      protocol: "TCP"
      port: 8080
  selector:
    name: "logcso-prod-ext-rcdn"
  type: "ClusterIP"
  sessionAffinity: "None"
---
kind: "Deployment"
apiVersion: "apps/v1"
metadata:
  annotations:
    lae_uuid: "logcsoprdlae-pmn6n54xprd"
  name: "logcso-prod-ext-rcdn"
spec:
  template:
    metadata:
      labels:
        name: "logcso-prod-ext-rcdn"
      annotations:
        app_version: 'latest'
    spec:
      imagePullSecrets:
        -
          name: "services-ts-others-sntcselfonboard-logcso-read-gen-pull-secret"    
      containers:
        - name: "logcso-prod-ext-rcdn"
          image: "containers.cisco.com/services_ts_others/sntcselfonboard_logcso:__IMAGETAG__"
          ports:
            - containerPort: 8080
              protocol: "TCP"
          env:
            - name: APPDYNAMICS_CONTROLLER_HOST_NAME
              value: "svc-ctrl-prd-01.cisco.com"
              
            - name: APPDYNAMICS_AGENT_ACCOUNT_NAME
              value: "customer1"
              
            - name: APPDYNAMICS_AGENT_APPLICATION_NAME
              value: "SSUE-PRD"
              
            - name: APPDYNAMICS_AGENT_TIER_NAME
              value: "logcso"
              
            - name: APPDYNAMICS_CONTROLLER_PORT
              value: "8090"
              
            - name: APPDYNAMICS_CONTROLLER_SSL_ENABLED
              value: "false"
              
            - name: APPDYNAMICS_AGENT_ACCOUNT_ACCESS_KEY
              value: "71bc2ae0-078c-406a-b886-f546eaccd5bd"
          
            - name: "OPENSHIFT_APP_NAME"
              value: "logcsoextrcdnprod"

            - name: "JAVA_OPTS_EXT"
              value: "-javaagent:/opt/AppDServerAgent/javaagent.jar -Dappdynamics.agent.nodeName=$HOSTNAME -XX:MaxMetaspaceSize=512m -XX:+AggressiveOpts -XX:MinHeapFreeRatio=20 -XX:MaxHeapFreeRatio=40 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90 -Djava.net.preferIPv4Stack=true -Dfile.encoding=UTF-8 -Djava.net.preferIPv4Stack=true -Dorg.apache.jasper.runtime.BodyContentImpl.LIMIT_BUFFER=true -Dorg.apache.jasper.runtime.JspFactoryImpl.USE_POOL=false -Dorg.apache.tomcat.util.http.ServerCookie.ALLOW_EQUALS_IN_VALUE=true -XX:+DisableExplicitGC -Xss512k -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=${OPENSHIFT_LOG_DIR} -verbose:gc -XX:+PrintGCDateStamps -XX:+PrintGCDetails -XX:+PrintGCApplicationStoppedTime -XX:+UseGCLogFileRotation -XX:GCLogFileSize=5M -XX:NumberOfGCLogFiles=4 -Xloggc:${OPENSHIFT_LOG_DIR}gc.log -XX:+PrintTenuringDistribution -XX:ActiveProcessorCount=8"

            - name: JAVA_HEAP_MIN_MAX
              value: "-Xms512m -Xmx2048m"
            
            - name: hostname
              valueFrom:
               fieldRef:
                apiVersion: v1
                fieldPath: spec.nodeName
             
          terminationGracePeriodSeconds: 30
          resources:
            limits:
              memory: 1.5Gi
            requests:
              cpu: .08
          volumeMounts:
            - name: podinfo
              mountPath: /etc/metadata
              readOnly: false
            - mountPath: "/opt/webserver/logs"
              name: "logcso-prod-ext-rcdn"
            - name: "logcso-prod-ext-rcdn-app-logs"
              mountPath: /home/jboss/lae-home/app-root/logs
            - name: "logcso-prod-ext-rcdn-app-data"
              mountPath: /home/jboss/data
            - name: "logcso-prod-ext-rcdn-app-tmp"
              mountPath: /tmp
          imagePullPolicy: "IfNotPresent"
          securityContext:
            capabilities: {}
            privileged: false
          #readinessProbe:
          #  httpGet:
          #    path: "/"
          #    port: 8080
          #  initialDelaySeconds: 15
          #  timeoutSeconds: 1
          #livenessProbe:
          #  exec:
          #    command:
          #      - "/bin/true"
          #  initialDelaySeconds: 15
          #  timeoutSeconds: 1
      volumes:
        - name: podinfo
          downwardAPI:
            items:
              - path: "labels"
                fieldRef:
                  fieldPath: metadata.labels
              -
                path: "annotations"
                fieldRef:
                  fieldPath: metadata.annotations
        - name: "logcso-prod-ext-rcdn"
          emptydir: {}
        - name: "logcso-prod-ext-rcdn-app-logs"
          emptydir: {}
        - name: "logcso-prod-ext-rcdn-app-data"
          emptydir: {}
        - name: "logcso-prod-ext-rcdn-app-tmp"
          emptydir: {}
      restartPolicy: "Always"
      dnsPolicy: "ClusterFirst"
  replicas: 1
  triggers:
    -
      type: "ConfigChange"
  strategy:
    type: "RollingUpdate"
    rollingParams:
      updatePeriodSeconds: 1
      intervalSeconds: 1
      timeoutSeconds: 300
